# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoAqar' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for VideoAqar

  pod 'GoogleMaps'

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

end